apiVersion: v1
kind: Service
metadata:
  name: pneumonia-api-service
spec:
  selector:
    app: pneumonia-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
